package com.mmorpg.entity.mob;

/** Generated by tools/import_bbmodels.py from the supplied 30-model catalogue. */
public final class ImportedMobs {
    public record Entry(String key, String name, int zone, float width, float height, float scale, boolean flying) {
        /** Taille de la boite de collision une fois le modele mis a l'echelle. */
        public float scaledWidth() { return width * scale; }
        public float scaledHeight() { return height * scale; }
    }
    public static final String[] ZONES = {"Forêt ancienne", "Marais", "Cryptes", "Terres gelées", "Désert volcanique", "Néant astral"};
    public static final Entry[] ALL = {
        new Entry("mousseux", "Mousseux", 0, 0.635f, 0.906f, 1.380f, false),
        new Entry("sanglier_ronce", "Sanglier ronce", 0, 0.582f, 0.919f, 1.469f, false),
        new Entry("archer_sylvestre", "Archer sylvestre", 0, 0.560f, 1.570f, 1.242f, false),
        new Entry("veilleur_champignon", "Veilleur champignon", 0, 0.609f, 1.291f, 1.433f, false),
        new Entry("colosse_racine", "Colosse racine", 0, 1.440f, 2.588f, 1.391f, false),
        new Entry("crapaud_venimeux", "Crapaud venimeux", 1, 0.691f, 0.757f, 1.453f, false),
        new Entry("limace_acide", "Limace acide", 1, 0.450f, 0.553f, 1.537f, false),
        new Entry("luciole_geante", "Luciole géante", 1, 0.795f, 0.870f, 1.437f, true),
        new Entry("sorcier_roseaux", "Sorcier des roseaux", 1, 0.573f, 1.759f, 1.137f, false),
        new Entry("hydre_marais", "Hydre des marais", 1, 1.482f, 2.166f, 1.477f, false),
        new Entry("osselet", "Osselet", 2, 0.450f, 1.087f, 1.242f, false),
        new Entry("araignee_os", "Araignée d’os", 2, 0.822f, 0.534f, 1.779f, false),
        new Entry("garde_funeraire", "Garde funéraire", 2, 0.615f, 1.886f, 1.113f, false),
        new Entry("spectre_enchaine", "Spectre enchaîné", 2, 0.610f, 1.275f, 1.569f, true),
        new Entry("roi_cryptes", "Roi des cryptes", 2, 0.930f, 2.197f, 1.457f, false),
        new Entry("renard_givre", "Renard de givre", 3, 0.486f, 1.483f, 0.877f, false),
        new Entry("scarabee_polaire", "Scarabée polaire", 3, 0.712f, 0.924f, 1.299f, false),
        new Entry("harpie_neiges", "Harpie des neiges", 3, 1.387f, 1.479f, 1.352f, true),
        new Entry("golem_iceberg", "Golem d’iceberg", 3, 1.118f, 2.077f, 1.541f, false),
        new Entry("wyrm_boreal", "Wyrm boréal", 3, 1.393f, 2.371f, 1.434f, false),
        new Entry("scorpion_cuivre", "Scorpion de cuivre", 4, 0.762f, 1.022f, 1.272f, false),
        new Entry("momie_dunes", "Momie des dunes", 4, 0.450f, 1.450f, 1.345f, false),
        new Entry("hyene_cendree", "Hyène cendrée", 4, 0.450f, 0.835f, 1.557f, false),
        new Entry("djinn_braises", "Djinn des braises", 4, 0.780f, 1.665f, 1.321f, true),
        new Entry("tortue_volcanique", "Tortue volcanique", 4, 0.796f, 1.012f, 1.383f, false),
        new Entry("mite_astrale", "Mite astrale", 5, 1.167f, 1.548f, 1.292f, true),
        new Entry("rodeur_vide", "Rôdeur du vide", 5, 0.450f, 0.975f, 1.538f, false),
        new Entry("oeil_chaos", "Œil du chaos", 5, 0.919f, 1.400f, 1.357f, true),
        new Entry("chevalier_fracture", "Chevalier fracturé", 5, 0.790f, 1.830f, 1.202f, true),
        new Entry("devoreur_etoiles", "Dévoreur d’étoiles", 5, 1.928f, 2.466f, 1.541f, true)
    };
}
