package com.mmorpg.entity.mob;

/** Generated by tools/import_bbmodels.py from the supplied 30-model catalogue. */
public final class ImportedMobs {
    public record Entry(String key, String name, int zone, float width, float height) {}
    public static final String[] ZONES = {"Forêt ancienne", "Marais", "Cryptes", "Terres gelées", "Désert volcanique", "Néant astral"};
    public static final Entry[] ALL = {
        new Entry("mousseux", "Mousseux", 0, 0.635f, 0.906f),
        new Entry("sanglier_ronce", "Sanglier ronce", 0, 0.582f, 0.919f),
        new Entry("archer_sylvestre", "Archer sylvestre", 0, 0.560f, 1.570f),
        new Entry("veilleur_champignon", "Veilleur champignon", 0, 0.609f, 1.291f),
        new Entry("colosse_racine", "Colosse racine", 0, 1.440f, 2.588f),
        new Entry("crapaud_venimeux", "Crapaud venimeux", 1, 0.691f, 0.757f),
        new Entry("limace_acide", "Limace acide", 1, 0.450f, 0.553f),
        new Entry("luciole_geante", "Luciole géante", 1, 0.795f, 0.870f),
        new Entry("sorcier_roseaux", "Sorcier des roseaux", 1, 0.573f, 1.759f),
        new Entry("hydre_marais", "Hydre des marais", 1, 1.482f, 2.166f),
        new Entry("osselet", "Osselet", 2, 0.450f, 1.087f),
        new Entry("araignee_os", "Araignée d’os", 2, 0.822f, 0.534f),
        new Entry("garde_funeraire", "Garde funéraire", 2, 0.615f, 1.886f),
        new Entry("spectre_enchaine", "Spectre enchaîné", 2, 0.610f, 1.275f),
        new Entry("roi_cryptes", "Roi des cryptes", 2, 0.930f, 2.197f),
        new Entry("renard_givre", "Renard de givre", 3, 0.486f, 1.483f),
        new Entry("scarabee_polaire", "Scarabée polaire", 3, 0.712f, 0.924f),
        new Entry("harpie_neiges", "Harpie des neiges", 3, 1.387f, 1.479f),
        new Entry("golem_iceberg", "Golem d’iceberg", 3, 1.118f, 2.077f),
        new Entry("wyrm_boreal", "Wyrm boréal", 3, 1.393f, 2.371f),
        new Entry("scorpion_cuivre", "Scorpion de cuivre", 4, 0.762f, 1.022f),
        new Entry("momie_dunes", "Momie des dunes", 4, 0.450f, 1.450f),
        new Entry("hyene_cendree", "Hyène cendrée", 4, 0.450f, 0.835f),
        new Entry("djinn_braises", "Djinn des braises", 4, 0.780f, 1.665f),
        new Entry("tortue_volcanique", "Tortue volcanique", 4, 0.796f, 1.012f),
        new Entry("mite_astrale", "Mite astrale", 5, 1.167f, 1.548f),
        new Entry("rodeur_vide", "Rôdeur du vide", 5, 0.450f, 0.975f),
        new Entry("oeil_chaos", "Œil du chaos", 5, 0.919f, 1.400f),
        new Entry("chevalier_fracture", "Chevalier fracturé", 5, 0.790f, 1.830f),
        new Entry("devoreur_etoiles", "Dévoreur d’étoiles", 5, 1.928f, 2.466f)
    };
}
