package com.mmorpg.entity.mob;

/** Generated by tools/import_bbmodels.py from the supplied 30-model catalogue. */
public final class ImportedMobs {
    public record Entry(String key, String name, int zone, float width, float height, float scale, boolean levitating) {
        /** Taille de la boite de collision une fois le modele mis a l'echelle. */
        /** Hauteur de lévitation (blocs) entre le sol et le bas du modèle. */
        public float hover() { return levitating ? 0.6f : 0f; }
        /** Boite de collision plafonnée (3.5 x 6) pour que les géants puissent apparaître et se déplacer. */
        public float scaledWidth() { return Math.min(3.5f, width * scale); }
        public float scaledHeight() { return Math.min(6f, height * scale + hover()); }
    }
    public static final String[] ZONES = {"Forêt ancienne", "Marais", "Cryptes", "Terres gelées", "Désert volcanique", "Néant astral"};
    public static final Entry[] ALL = {
        new Entry("mousseux", "Mousseux", 0, 0.635f, 0.906f, 2.759f, false),
        new Entry("sanglier_ronce", "Sanglier ronce", 0, 0.582f, 0.919f, 2.936f, false),
        new Entry("archer_sylvestre", "Archer sylvestre", 0, 0.560f, 1.570f, 2.484f, false),
        new Entry("veilleur_champignon", "Veilleur champignon", 0, 0.609f, 1.291f, 2.867f, false),
        new Entry("colosse_racine", "Colosse racine", 0, 1.440f, 2.588f, 4.174f, false),
        new Entry("crapaud_venimeux", "Crapaud venimeux", 1, 0.691f, 0.757f, 2.906f, false),
        new Entry("limace_acide", "Limace acide", 1, 0.450f, 0.553f, 3.073f, false),
        new Entry("luciole_geante", "Luciole géante", 1, 0.795f, 0.870f, 2.873f, true),
        new Entry("sorcier_roseaux", "Sorcier des roseaux", 1, 0.573f, 1.759f, 2.274f, false),
        new Entry("hydre_marais", "Hydre des marais", 1, 1.482f, 2.166f, 4.433f, false),
        new Entry("osselet", "Osselet", 2, 0.450f, 1.087f, 2.483f, false),
        new Entry("araignee_os", "Araignée d’os", 2, 0.822f, 0.534f, 3.556f, false),
        new Entry("garde_funeraire", "Garde funéraire", 2, 0.615f, 1.886f, 2.227f, false),
        new Entry("spectre_enchaine", "Spectre enchaîné", 2, 0.610f, 1.275f, 3.137f, true),
        new Entry("roi_cryptes", "Roi des cryptes", 2, 0.930f, 2.197f, 4.369f, false),
        new Entry("renard_givre", "Renard de givre", 3, 0.486f, 1.483f, 1.753f, false),
        new Entry("scarabee_polaire", "Scarabée polaire", 3, 0.712f, 0.924f, 2.598f, false),
        new Entry("harpie_neiges", "Harpie des neiges", 3, 1.387f, 1.479f, 2.705f, true),
        new Entry("golem_iceberg", "Golem d’iceberg", 3, 1.118f, 2.077f, 4.621f, false),
        new Entry("wyrm_boreal", "Wyrm boréal", 3, 1.393f, 2.371f, 4.302f, false),
        new Entry("scorpion_cuivre", "Scorpion de cuivre", 4, 0.762f, 1.022f, 2.544f, false),
        new Entry("momie_dunes", "Momie des dunes", 4, 0.450f, 1.450f, 2.690f, false),
        new Entry("hyene_cendree", "Hyène cendrée", 4, 0.450f, 0.835f, 3.113f, false),
        new Entry("djinn_braises", "Djinn des braises", 4, 0.780f, 1.665f, 2.643f, true),
        new Entry("tortue_volcanique", "Tortue volcanique", 4, 0.796f, 1.012f, 2.765f, false),
        new Entry("mite_astrale", "Mite astrale", 5, 1.167f, 1.548f, 2.583f, true),
        new Entry("rodeur_vide", "Rôdeur du vide", 5, 0.450f, 0.975f, 3.077f, false),
        new Entry("oeil_chaos", "Œil du chaos", 5, 0.919f, 1.400f, 2.714f, true),
        new Entry("chevalier_fracture", "Chevalier fracturé", 5, 0.790f, 1.830f, 2.404f, false),
        new Entry("devoreur_etoiles", "Dévoreur d’étoiles", 5, 1.928f, 2.466f, 6.163f, false)
    };
}
